version: "3"
services:
  api:
    container_name: api
    build: ./api
    env_file: ./api/.env
    ports:
      - "5000:5000"
    links:
      - db
  web:
    container_name: web
    build: ./web
    ports:
      - "4200:4200"
    links:
      - api
  db:
    container_name: db
    image: postgres:9.6.1
    environment:
      - POSTGRES_USER=docker
      - POSTGRES_PASSWORD=docker
      - POSTGRES_DB=extremelySAFUPassword
    ports:
      - "5432:5432"
